{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "from tensorflow import keras\n",
    "from src.utils import to_csv\n",
    "from src.train import train_test_split, build_tl_2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Found 2436 files belonging to 7 classes.\n",
      "Using 1706 files for training.\n",
      "Found 2436 files belonging to 7 classes.\n",
      "Using 1706 files for training.\n"
     ]
    }
   ],
   "source": [
    "train, val = train_test_split('./dataset')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/20\n"
     ]
    },
    {
     "ename": "ResourceExhaustedError",
     "evalue": "Graph execution error:\n\nDetected at node 'model/conv4_block15_1_conv/Conv2D' defined at (most recent call last):\n    File \"C:\\Users\\acard\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"C:\\Users\\acard\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\traitlets\\config\\application.py\", line 965, in launch_instance\n      app.start()\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n      self.io_loop.start()\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"C:\\Users\\acard\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 600, in run_forever\n      self._run_once()\n    File \"C:\\Users\\acard\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 1896, in _run_once\n      handle._run()\n    File \"C:\\Users\\acard\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 504, in dispatch_queue\n      await self.process_one()\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 493, in process_one\n      await dispatch(*args)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 400, in dispatch_shell\n      await result\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 724, in execute_request\n      reply_content = await reply_content\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n      res = shell.run_cell(\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2880, in run_cell\n      result = self._run_cell(\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2935, in _run_cell\n      return runner(coro)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3134, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3337, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3397, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"C:\\Users\\acard\\AppData\\Local\\Temp\\ipykernel_24284\\2529645484.py\", line 1, in <cell line: 1>\n      model, history = build_tl_2(keras.applications.DenseNet121, 7, train, val, epochs=20)\n    File \"c:\\Users\\acard\\Documents\\GitHub\\Lavoro\\Poliba\\Vulma\\bridge_vulma\\src\\train\\train.py\", line 93, in build_tl_2\n      history = model.fit(train, epochs=epochs, validation_data=val)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\engine\\training.py\", line 1384, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function\n      return step_function(self, iterator)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\engine\\functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\engine\\functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\layers\\convolutional.py\", line 248, in call\n      outputs = self.convolution_op(inputs, self.kernel)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\layers\\convolutional.py\", line 233, in convolution_op\n      return tf.nn.convolution(\nNode: 'model/conv4_block15_1_conv/Conv2D'\nOOM when allocating tensor with shape[32,128,14,14] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n\t [[{{node model/conv4_block15_1_conv/Conv2D}}]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n [Op:__inference_train_function_25432]",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mResourceExhaustedError\u001b[0m                    Traceback (most recent call last)",
      "\u001b[1;32mc:\\Users\\acard\\Documents\\GitHub\\Lavoro\\Poliba\\Vulma\\bridge_vulma\\dl2.ipynb Cell 3'\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[1;34m()\u001b[0m\n\u001b[1;32m----> <a href='vscode-notebook-cell:/c%3A/Users/acard/Documents/GitHub/Lavoro/Poliba/Vulma/bridge_vulma/dl2.ipynb#ch0000002?line=0'>1</a>\u001b[0m model, history \u001b[39m=\u001b[39m build_tl_2(keras\u001b[39m.\u001b[39;49mapplications\u001b[39m.\u001b[39;49mDenseNet121, \u001b[39m7\u001b[39;49m, train, val, epochs\u001b[39m=\u001b[39;49m\u001b[39m20\u001b[39;49m)\n",
      "File \u001b[1;32mc:\\Users\\acard\\Documents\\GitHub\\Lavoro\\Poliba\\Vulma\\bridge_vulma\\src\\train\\train.py:93\u001b[0m, in \u001b[0;36mbuild_tl_2\u001b[1;34m(model_builder, n_classes, train, val, img_width, img_height, n_channels, epochs, optimizer, loss, metrics)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/Users/acard/Documents/GitHub/Lavoro/Poliba/Vulma/bridge_vulma/src/train/train.py?line=84'>85</a>\u001b[0m model \u001b[39m=\u001b[39m keras\u001b[39m.\u001b[39mmodels\u001b[39m.\u001b[39mModel(\n\u001b[0;32m     <a href='file:///c%3A/Users/acard/Documents/GitHub/Lavoro/Poliba/Vulma/bridge_vulma/src/train/train.py?line=85'>86</a>\u001b[0m     inputs\u001b[39m=\u001b[39mmodel\u001b[39m.\u001b[39minputs,\n\u001b[0;32m     <a href='file:///c%3A/Users/acard/Documents/GitHub/Lavoro/Poliba/Vulma/bridge_vulma/src/train/train.py?line=86'>87</a>\u001b[0m     outputs\u001b[39m=\u001b[39moutput)\n\u001b[0;32m     <a href='file:///c%3A/Users/acard/Documents/GitHub/Lavoro/Poliba/Vulma/bridge_vulma/src/train/train.py?line=87'>88</a>\u001b[0m model\u001b[39m.\u001b[39mcompile(\n\u001b[0;32m     <a href='file:///c%3A/Users/acard/Documents/GitHub/Lavoro/Poliba/Vulma/bridge_vulma/src/train/train.py?line=88'>89</a>\u001b[0m     optimizer\u001b[39m=\u001b[39moptimizer,\n\u001b[0;32m     <a href='file:///c%3A/Users/acard/Documents/GitHub/Lavoro/Poliba/Vulma/bridge_vulma/src/train/train.py?line=89'>90</a>\u001b[0m     loss\u001b[39m=\u001b[39mloss,\n\u001b[0;32m     <a href='file:///c%3A/Users/acard/Documents/GitHub/Lavoro/Poliba/Vulma/bridge_vulma/src/train/train.py?line=90'>91</a>\u001b[0m     metrics\u001b[39m=\u001b[39mmetrics\n\u001b[0;32m     <a href='file:///c%3A/Users/acard/Documents/GitHub/Lavoro/Poliba/Vulma/bridge_vulma/src/train/train.py?line=91'>92</a>\u001b[0m )\n\u001b[1;32m---> <a href='file:///c%3A/Users/acard/Documents/GitHub/Lavoro/Poliba/Vulma/bridge_vulma/src/train/train.py?line=92'>93</a>\u001b[0m history \u001b[39m=\u001b[39m model\u001b[39m.\u001b[39;49mfit(train, epochs\u001b[39m=\u001b[39;49mepochs, validation_data\u001b[39m=\u001b[39;49mval)\n\u001b[0;32m     <a href='file:///c%3A/Users/acard/Documents/GitHub/Lavoro/Poliba/Vulma/bridge_vulma/src/train/train.py?line=93'>94</a>\u001b[0m \u001b[39mreturn\u001b[39;00m model, history\n",
      "File \u001b[1;32mc:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\utils\\traceback_utils.py:67\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/Users/acard/.virtualenvs/bridge-vulma_v3-TYdCAC2x/lib/site-packages/keras/utils/traceback_utils.py?line=64'>65</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:  \u001b[39m# pylint: disable=broad-except\u001b[39;00m\n\u001b[0;32m     <a href='file:///c%3A/Users/acard/.virtualenvs/bridge-vulma_v3-TYdCAC2x/lib/site-packages/keras/utils/traceback_utils.py?line=65'>66</a>\u001b[0m   filtered_tb \u001b[39m=\u001b[39m _process_traceback_frames(e\u001b[39m.\u001b[39m__traceback__)\n\u001b[1;32m---> <a href='file:///c%3A/Users/acard/.virtualenvs/bridge-vulma_v3-TYdCAC2x/lib/site-packages/keras/utils/traceback_utils.py?line=66'>67</a>\u001b[0m   \u001b[39mraise\u001b[39;00m e\u001b[39m.\u001b[39mwith_traceback(filtered_tb) \u001b[39mfrom\u001b[39;00m \u001b[39mNone\u001b[39m\n\u001b[0;32m     <a href='file:///c%3A/Users/acard/.virtualenvs/bridge-vulma_v3-TYdCAC2x/lib/site-packages/keras/utils/traceback_utils.py?line=67'>68</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m     <a href='file:///c%3A/Users/acard/.virtualenvs/bridge-vulma_v3-TYdCAC2x/lib/site-packages/keras/utils/traceback_utils.py?line=68'>69</a>\u001b[0m   \u001b[39mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[1;32mc:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py:54\u001b[0m, in \u001b[0;36mquick_execute\u001b[1;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/Users/acard/.virtualenvs/bridge-vulma_v3-TYdCAC2x/lib/site-packages/tensorflow/python/eager/execute.py?line=51'>52</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m     <a href='file:///c%3A/Users/acard/.virtualenvs/bridge-vulma_v3-TYdCAC2x/lib/site-packages/tensorflow/python/eager/execute.py?line=52'>53</a>\u001b[0m   ctx\u001b[39m.\u001b[39mensure_initialized()\n\u001b[1;32m---> <a href='file:///c%3A/Users/acard/.virtualenvs/bridge-vulma_v3-TYdCAC2x/lib/site-packages/tensorflow/python/eager/execute.py?line=53'>54</a>\u001b[0m   tensors \u001b[39m=\u001b[39m pywrap_tfe\u001b[39m.\u001b[39mTFE_Py_Execute(ctx\u001b[39m.\u001b[39m_handle, device_name, op_name,\n\u001b[0;32m     <a href='file:///c%3A/Users/acard/.virtualenvs/bridge-vulma_v3-TYdCAC2x/lib/site-packages/tensorflow/python/eager/execute.py?line=54'>55</a>\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[0;32m     <a href='file:///c%3A/Users/acard/.virtualenvs/bridge-vulma_v3-TYdCAC2x/lib/site-packages/tensorflow/python/eager/execute.py?line=55'>56</a>\u001b[0m \u001b[39mexcept\u001b[39;00m core\u001b[39m.\u001b[39m_NotOkStatusException \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m     <a href='file:///c%3A/Users/acard/.virtualenvs/bridge-vulma_v3-TYdCAC2x/lib/site-packages/tensorflow/python/eager/execute.py?line=56'>57</a>\u001b[0m   \u001b[39mif\u001b[39;00m name \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n",
      "\u001b[1;31mResourceExhaustedError\u001b[0m: Graph execution error:\n\nDetected at node 'model/conv4_block15_1_conv/Conv2D' defined at (most recent call last):\n    File \"C:\\Users\\acard\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"C:\\Users\\acard\\AppData\\Local\\Programs\\Python\\Python310\\lib\\runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\traitlets\\config\\application.py\", line 965, in launch_instance\n      app.start()\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n      self.io_loop.start()\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n      self.asyncio_loop.run_forever()\n    File \"C:\\Users\\acard\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 600, in run_forever\n      self._run_once()\n    File \"C:\\Users\\acard\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\base_events.py\", line 1896, in _run_once\n      handle._run()\n    File \"C:\\Users\\acard\\AppData\\Local\\Programs\\Python\\Python310\\lib\\asyncio\\events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 504, in dispatch_queue\n      await self.process_one()\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 493, in process_one\n      await dispatch(*args)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 400, in dispatch_shell\n      await result\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 724, in execute_request\n      reply_content = await reply_content\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 383, in do_execute\n      res = shell.run_cell(\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2880, in run_cell\n      result = self._run_cell(\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2935, in _run_cell\n      return runner(coro)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3134, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3337, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3397, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"C:\\Users\\acard\\AppData\\Local\\Temp\\ipykernel_24284\\2529645484.py\", line 1, in <cell line: 1>\n      model, history = build_tl_2(keras.applications.DenseNet121, 7, train, val, epochs=20)\n    File \"c:\\Users\\acard\\Documents\\GitHub\\Lavoro\\Poliba\\Vulma\\bridge_vulma\\src\\train\\train.py\", line 93, in build_tl_2\n      history = model.fit(train, epochs=epochs, validation_data=val)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\engine\\training.py\", line 1384, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\engine\\training.py\", line 1021, in train_function\n      return step_function(self, iterator)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\engine\\training.py\", line 1010, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\engine\\training.py\", line 1000, in run_step\n      outputs = model.train_step(data)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\engine\\training.py\", line 859, in train_step\n      y_pred = self(x, training=True)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\engine\\functional.py\", line 451, in call\n      return self._run_internal_graph(\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\engine\\functional.py\", line 589, in _run_internal_graph\n      outputs = node.layer(*args, **kwargs)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1096, in __call__\n      outputs = call_fn(inputs, *args, **kwargs)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 92, in error_handler\n      return fn(*args, **kwargs)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\layers\\convolutional.py\", line 248, in call\n      outputs = self.convolution_op(inputs, self.kernel)\n    File \"c:\\Users\\acard\\.virtualenvs\\bridge-vulma_v3-TYdCAC2x\\lib\\site-packages\\keras\\layers\\convolutional.py\", line 233, in convolution_op\n      return tf.nn.convolution(\nNode: 'model/conv4_block15_1_conv/Conv2D'\nOOM when allocating tensor with shape[32,128,14,14] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc\n\t [[{{node model/conv4_block15_1_conv/Conv2D}}]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n [Op:__inference_train_function_25432]"
     ]
    }
   ],
   "source": [
    "model, history = build_tl_2(keras.applications.DenseNet121, 7, train, val, epochs=20)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "model.save('mobilenet.h5')\n",
    "to_csv(history.history, outfile='history_mobile.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "78128ea9911bfd6521b4706837ad107bf9b1e8e6586200bf5e0f9634179147f0"
  },
  "kernelspec": {
   "display_name": "Python 3.10.4 ('bridge-vulma_v3-TYdCAC2x')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.4"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
